spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/film-track-app?serverTimezone=UTC}
    username: root
    password:
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  task:
    scheduling:
      pool:
        size: 2
springdoc:
  pathsToMatch: /api/**

logging:
  level:
    org:
      hibernate:
#        SQL: DEBUG
        type:
          descriptor:
            sql:
#              BasicBinder: TRACE


